package poc.rcm.calculadoraservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0-SNAPSHOT
 * 2012-04-10T12:28:17.116-05:00
 * Generated source version: 2.6.0-SNAPSHOT
 * 
 */
@WebService(targetNamespace = "http://rcm.poc/CalculadoraService/", name = "CalculadoraService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CalculadoraService {

    @WebResult(name = "Resultado", targetNamespace = "http://rcm.poc/CalculadoraService/", partName = "parameters")
    @WebMethod(action = "http://rcm.poc/CalculadoraService/sumar")
    public ResultadoType sumar(
        @WebParam(partName = "parameters", name = "Argumentos", targetNamespace = "http://rcm.poc/CalculadoraService/")
        ArgumentosType parameters
    );
}
