package poc.rcm.calculadoraservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0-SNAPSHOT
 * 2012-04-10T12:28:17.159-05:00
 * Generated source version: 2.6.0-SNAPSHOT
 * 
 */
@WebServiceClient(name = "CalculadoraService", 
                  wsdlLocation = "file:/C:/Users/ricardo/Documents/poc/workspace/suma_wsdl/api/src/main/resources/CalculadoraService.wsdl",
                  targetNamespace = "http://rcm.poc/CalculadoraService/") 
public class CalculadoraService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rcm.poc/CalculadoraService/", "CalculadoraService");
    public final static QName CalculadoraServiceSOAP = new QName("http://rcm.poc/CalculadoraService/", "CalculadoraServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ricardo/Documents/poc/workspace/suma_wsdl/api/src/main/resources/CalculadoraService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ricardo/Documents/poc/workspace/suma_wsdl/api/src/main/resources/CalculadoraService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CalculadoraService
     */
    @WebEndpoint(name = "CalculadoraServiceSOAP")
    public CalculadoraService getCalculadoraServiceSOAP() {
        return super.getPort(CalculadoraServiceSOAP, CalculadoraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraService
     */
    @WebEndpoint(name = "CalculadoraServiceSOAP")
    public CalculadoraService getCalculadoraServiceSOAP(WebServiceFeature... features) {
        return super.getPort(CalculadoraServiceSOAP, CalculadoraService.class, features);
    }

}
